### ISSUE TITLE
zef does not default to $HOME/.perl6 for non-root users

### ISSUE THREAD

**Issue by gfldex** [ugexe/zef#103]
On a system where rakudo is installed as root and the main CompUnit::Repository is unwriteable, zef does not fall back to install modules under $HOME.

`zef --install-to=home insall Any::Module::You::Like` just works, so it seams to be a matter of detection, not inability.

**Comment by ugexe** [comment]
This can be worked around currently by setting https://github.com/ugexe/zef/blob/1e7e1cdb143e3478d3367a2bda00513375b6826d/resources/config.json#L6

Note that the config file that gets loaded is `first *.e, $*HOME.child('.zef').child('config.json'), %?RESOURCES<config.json>;` so you can set it per-user while root retains the original config in %?RESOURCES (`zef --help` shows which config file its using for this purpose). Or you can edit `resources/config.json` before installing zef to have those changes take affect globally.

**Comment by vadz** [comment]
I'd like to add that this is very non-obvious to find: I tried using something like `--install-to=~/perl6/site` and was given just `CompUnit::Repository install target is not writeable/installable: /home/zeitlin/perl6/site` message that is not clear at all. It would be nice if help output could mention that just "home" works (although I'd still prefer to use my own directory and still don't know how to do it).

**Comment by ugexe** [comment]
It's explicitly mentioned in the README [here](https://github.com/ugexe/zef#custom-installation-locations)

    Pass a path to the -to / --install-to option and prefix the path with `inst#` (unless you know what you're doing)

In Perl6 you don't *have* to install to a CompUnit::Repository::Installation, only a repository that is `CompUnit::Repository::Installable`. Hence prefixing the short-id of the repo you are targeting (in this case `inst#`). `home` and `site` are short-names of `CompUnit::Repository::Installation` instances, but there currently is no way to pull the available list of these short-names from rakudo so you very well may not have a `home` or `site` available (which is why there is no hard coded message in zef telling you to use them as they may not exist). When this is eventually exposed in the Rakudo's CUR interface then it will be able to report possible short-name targets.
