### ISSUE TITLE
===> Found via ... spilled into list of modules

### ISSUE THREAD

**Issue by gfldex** [ugexe/zef#104]
This is human-readable but machine confusing. A safe default would be to output this info only if --verbose is asked for. UPDATE: (for zef list)

**Comment by ugexe** [comment]
I agree. But what about when you have the same module installed to multiple CURs?

The `===>` is shown so that situation makes more sense (showing the same module 2+ times). Some solutions:
* 1) Prepend the CUR string to each distribution that is listed (not very human readable)
* 2) Only list the unique distribution identities (this seems less than ideal)

**Comment by gfldex** [comment]
maybe provide it like so:
Math::FourierTransform:ver('0.0.1'):auth('Matt Oates'):CUR('Zef::ContentStorage::Ecosystems<p6c>')

If you want to work with those outputs one has to parse :foo('bar') anyway.

**Comment by ugexe** [comment]
I'll think on this a few more days. I don't really like the repeating `:CUR('xxx')` for each line on non-verbose output, but I'm not discounting it either.

In the mean time the following can be used to show an example of your proposal:

    # list from all content storages
    perl6 -MZef::Client -MZef::Config -e '.say for Zef::Client.new(config => Zef::Config::parse-file(Zef::Config::guess-path)).list-available().map: { qq|{.dist.identity}:CUR("{.from}")| };'

    # list from perl6 ecosystem content storage only
    perl6 -MZef::Client -MZef::Config -e '.say for Zef::Client.new(config => Zef::Config::parse-file(Zef::Config::guess-path)).list-available("p6c").map: { qq|{.dist.identity}:CUR("{.from}")| };'

**Comment by ugexe** [comment]
Resolved in #151
