### ISSUE TITLE
git clone can hang a very long time

### ISSUE THREAD

**Issue by gfldex** [ugexe/zef#105]
I'm currently installing all modules. While doing so I observed a git clone (via ssh) that was sleeping for more then one hour. It may be useful to have a timeout on git and produce an error message.

I killed the git process by hand and zef exited without producing any message. Testing this could be done by providing a shellscript named git that sleeps for some time.

**Comment by ugexe** [comment]
One way to do this is to configure `git` itself to timeout with the ENV var `GIT_HTTP_LOW_SPEED_TIME`, although that doesn't help with the message.

I'll think on the best way to do this otherwise - I want to avoid spawning an extra timeout tracking thread for each download. Maybe it should insist on using git/wget/whatever ENV vars to handle it on a per-download basis but have an overall progress timeout at the perl6/zef level (so only 1 additional thread)

**Comment by gfldex** [comment]
This is how I solved that problem in META6::bin

```
my $git = Proc::Async.new('git', '-C', $base-dir, 'remote', 'add', 'origin', "https://github.com/$github-user/$base-dir");
my $timeout = Promise.at(now + 60);
    
await Promise.anyof($p = $git.start, $timeout);
fail "⟨git remote⟩ timed out." if $p.status == Broken;
```

**Comment by ugexe** [comment]
I'm wary of using Proc::Async until it works on the JVM

**Comment by ugexe** [comment]
Another note other than the JVM bit (around 2015 when zef still did concurrency it used `Proc::Async` but I switched to regular `Proc` + `start { }` to work with JVM before having to remove concurrency entirely): Ideally all fetchers share a common timeout option, so such functionality would need to be more generic (probably handled in `Zef::Fetch` on each individual adapter).
