### ISSUE TITLE
zef doesn't report own version

### ISSUE THREAD

**Issue by coke** [ugexe/zef#122]
When reporting issues with modules in the ecosystem, I'd like to have an easy way to say which version of zef I'm using in the installer, e.g.:

```
zef --version
```

**Comment by coke** [comment]
Note that even this doesn't report the version:

```
$ zef list --installed | grep zef
zef:auth('github:ugexe')
```

**Comment by ugexe** [comment]
fwiw it doesn't report a version for that command because it's version is "whatever" / "*", which is the same as not having a `:ver<...>` (e.g. `use zef:auth('github:ugexe')` and `use zef:auth('github:ugexe'):ver<*>` are the same).

To rephrase the issue: zef should start versioning itself

...to which I would respond: yeah I probably should. I never bothered because back versions aren't really a thing in the ecosystem yet, and ^HEAD zef should work on all v6.c rakudo still

**Comment by zoffixznet** [comment]
:+1: I needed a version once to see if I'm on latest enough zef

**Comment by ugexe** [comment]
# lib/Zef/CLI.pm

    ...

    #| Show current version information for zef
    multi MAIN('version') is export {
        say $*REPO.need(CompUnit::DependencySpecification.new(:short-name('Zef::Client'))).distribution.meta<version>;
    }

FWIW I'm not ignoring this. I'm trying to find a way for zef to actually report the version that is being run from its own META6 data, which may or may not be installed. The above works when the CompUnit comes from some CURs but not others.

Or we could implement `%?META` or `%?DISTRIBUTION` in rakudo, similar to `%?RESOURCES`

**Comment by ugexe** [comment]
For the moment `zef info zef` will give you the version for zef (but only if its an installed version e.g. from CURI)

```
nickl@li685-90:~/perl6/zef$ zef info zef
- Info for: zef
- Identity: zef:ver('0.1.0'):auth('github:ugexe')
- Recommended By: /home/nickl/.rakudobrew/moar-blead-nom/install/share/perl6/site
Description:     It's like [cpanm] wearing high heels with a tracksuit
Source-url:      git://github.com/ugexe/zef.git
Provides: 34 modules
Support:
#   bugtracker: https://github.com/ugexe/zef/issues
Depends: 0 items
```
