### ISSUE TITLE
Zef ignores git config settings

### ISSUE THREAD

**Issue by wbiker** [ugexe/zef#123]
On my network, the git protocoll is blocked, so my git config looks like this:
[url "https://"]
    insteadOf = git://

Installing Hiker via zef causes a lot of errors like:
zef install Hiker
===> Searching for: Hiker
===> Searching for missing dependencies: HTTP::Server::Async, HTTP::Server::Router, Template::Mustache
===> Fetching: Hiker
===> Fetching: HTTP::Server::Router
===> Fetching: Template::Mustache
===> Fetching: HTTP::Server::Async
===> Testing: HTTP::Server::Router:ver('0.1.0'):auth('github:tony-o')
===SORRY!===
Could not find HTTP::Server:auth<github:tony-o> at line 1 in:
    StackTrace
===> Testing [FAIL]: HTTP::Server::Router:ver('0.1.0'):auth('github:tony-o')

Installing via panda works just fine. So, I think zef ignores the url.insteadOf setting?

**Comment by ugexe** [comment]
I don't think this is related to git because it looks like it downloaded everything fine, so I'm closing this. If you wish to reopen it under a different title feel free to do so, but also include your `perl6 -v`, the results from running with `zef --debug install Hiker`, and the full stack traces.

There is a *compile time* error from when one of the dependencies is first loaded during the test phase. For all I know it might work if you tried it a second time, and the only reason it worked with panda was because it *had already been run once* before by zef (and thus partially precompiled already).

**Comment by ugexe** [comment]
One more idea would be to try with `zef --/tap-harness install Hiker`. If it only works with that `--/tap-harness` command (which disables the p6 harness makes it use the same test harness as panda) then it could be a bug in rakudo or the perl6 tap harness.
