### ISSUE TITLE
zef installs programs under $HOME/.perl6/ which is silly. 

### ISSUE THREAD

**Issue by RichardWilliamPearse** [ugexe/zef#133]
## Context
Forcing or even documenting an option to install packages somewhere reasonable - like /usr/local/* or somewhere in the path - would be a good improvement. 

## Your Environment
This is Rakudo version 2016.12 built on MoarVM version 2016.12
implementing Perl 6.c.

Linux  4.9.0-1-686-pae #1 SMP Debian 4.9.2-2 (2017-01-12) i686 GNU/Linux

**Comment by ugexe** [comment]
First let me prefix this comment with https://github.com/ugexe/zef#custom-installation-locations - This doesn't address your concern directly but *does* document the long way of solving the problem.

To answer *how* to do this now - edit https://github.com/ugexe/zef/blob/master/resources/config.json#L6 to one of:

* `home` or `site` - These are the default repo names which are mapped to paths in Rakudo itself. You can see these paths by running `perl6 -e 'say CompUnit::RepositoryRegistry.repository-for-name("$_") for <site home>'`
* `auto` - Will install to `site` if it has write permissions, otherwise it will fallback to `home`. Zef specific. This allows a global `zef` installation that installs to the system perl6 if it has permissions and $*HOME/.perl6 otherwise. 
* `$some-path` - Zef specific


You can either edit the file prior to installing zef, place a copy of the edited file inside `$*HOME/.zef/`, or run `zef --help` and edit the file shown after `CONFIGURATION`.

Addressing the *why* regarding defaulting to site/home ($*HOME/.perl6): Its Rakudo [default](https://github.com/rakudo/rakudo/blob/960a78900dd140c28b62106b3ae8ed0c41799ab9/src/core/CompUnit/RepositoryRegistry.pm#L86) [behavior](https://github.com/rakudo/rakudo/blob/960a78900dd140c28b62106b3ae8ed0c41799ab9/src/core/CompUnit/RepositoryRegistry.pm#L93), making them good default candidates.

So this may be something you wish to address on irc freenode `#perl6-toolchain` and `#perl6`. Because, while it would be trivial for me to change the default to something else, it means tools other than `zef` would not be able to find these locations (e.g. it may make more sense to implement different "sane" defaults in Rakudo).

**Comment by RichardWilliamPearse** [comment]
> First let me prefix this comment with https://github.com/ugexe/zef#custom-installation-locations - 

Oh, yes, well that's the answer. I read and tried the CPAN section immediately above, how did I not see that? 

And I see what you are saying, that you are constrained by the Rakudo defaults. 

I have changed the config file as you have suggested and will reinstall now. Thanks for your help.
