### ISSUE TITLE
"$ zef build $PWD" hangs

### ISSUE THREAD

**Issue by titsuki** [ugexe/zef#166]
`$ zef build $PWD` hangs when it is executed in travis-ci environments.

## Context
Recently, `panda` was deprecated and `zef` was recommended to use for module installations.
According to the above recommendation, I had to fix my `.travis.yaml`, because it calls `panda` inside its script.

My previous one (It had been working well for several months):
```
os:
  - linux
  - osx
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
script:
  - perl6 -MPanda::Builder -e 'Panda::Builder.build(~$*CWD)'
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
````

I thought that the zef-counterpart of:
+ `panda --notests installdeps .` is `zef install --depsonly --/test --/build .`
+ `perl6 -MPanda::Builder -e 'Panda::Builder.build(~$*CWD)'` is `zef build $PWD`. 

So I fixed my `.travis.yaml` as the following:
```
os:
  - linux
  - osx
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef install --depsonly --/test --/build .
script:
  - zef build $PWD
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
```

However, it hangs when `zef build $PWD` is called. 

## Expected Behavior
`$ zef build $PWD` doesn't hang and outputs its intermediate status to the terminal.

## Actual Behavior
`$ zef build $PWD` hangs.

## Steps to Reproduce

```
$ git clone --depth=50 --branch=fix-travis https://github.com/titsuki/p6-Chart-Gnuplot.git titsuki/p6-Chart-Gnuplot
$ cd titsuki/p6-Chart-Gnuplot
$ git checkout -qf f08b6b92ec0515000d584ed03cad0bc23d15608f
$ rakudobrew build moar
$ rakudobrew build-zef
$ zef install --depsonly --/test --/build .
$ zef build $PWD
```

See also:
https://travis-ci.org/titsuki/p6-Chart-Gnuplot/jobs/234493570

## Your Environment
```
$ perl6 --version
This is Rakudo version 2017.05-5-g15a6f77 built on MoarVM version 2017.05
```

**Comment by titsuki** [comment]
Sorry, I noticed that:
+ panda uses `class Build` in Build.pm
+ panda uses `class Builder` in Build.pm

I used `class Build` in Build.pm for zef by mistake.
After fixing this issue, it doesn't hang anymore, but still fails.

**Comment by ugexe** [comment]
Plenty of modules use Build.pm and install with zef. If it worked with panda but not zef it is merely coincidental or indicative of a Rakudo bug.

If you run zef with --debug it will output the command that zef uses to run your Build.pm. You can use this to tweak and test your Build.pm to figure out where exactly it's breaking

**Comment by ugexe** [comment]
Also it is supposed to be class Build, not Builder. The only reason it gets further if you change that is because it fails precompiling instead of dead locking.

**Comment by titsuki** [comment]
@ugexe 
Thanks for your reply!

I tried with `--debug` option and `class Build`, then`zef` outputs the following messages and hangs:
```
$ zef --debug build . 
===> Building: Chart::Gnuplot
Building with plugin: Zef::Service::Shell::Build+{<anon|93285280>}
Command: /home/itoyota/.rakudobrew/bin/../moar-nom/install/bin/perl6 -Ilib -I. -MBuild -e ::('Build').new.build('/home/itoyota/Programs/p6-Chart-Gnuplot'); exit(0);
# hangs
```

However, I found that if I run the above command independently (i.e. directly input the command to the terminal), it works well:
```
$ /home/itoyota/.rakudobrew/bin/../moar-nom/install/bin/perl6 -Ilib -I. -MBuild -e '::("Build").new.build("/home/itoyota/Programs/p6-Chart-Gnuplot"); exit(0);'
# start build process
````

**Comment by ugexe** [comment]
So next maybe try to insert debug statements in each line, try removing code until it works with zef, etc.

The deadlock is referred to as "the open3 problem" if this is what I think it is, but that also means you may be able to work around it by changing/reordering/removing what the Build.pm outputs to stdout/stderr

**Comment by titsuki** [comment]
@ugexe
Thanks again!
I'll try it later.

**Comment by ugexe** [comment]
Actually all you will be able to do is *remove* code and figure out exactly which line causes the problem.

You won't be able to add say/note to use debug output because zef captures those from the process it launches without modifying zef code. You can add such debugging stuff here:
https://github.com/ugexe/zef/blob/master/lib/Zef/Service/Shell/Build.pm6#L95-L104
(Note that this section of code is also where the deadlock would be occurring) I don't expect you to modify any of that, but that's what I will end up doing to debug so I figured I'd inform you in case you want to.

**Comment by titsuki** [comment]
@ugexe
Thanks!
I found that `wget` is the cause of this hanging.

> Note that we (perl6 toolchain collaborators) have a replacement for Build.pm designed 

Then I'll stay tuned for something make things better :)

**Comment by ugexe** [comment]
Hmm so I think this is a bug with rakudo and `.exitcode`. I ran into this exact same problem last night. [See code and comments](https://github.com/ugexe/Perl6-App--ecogen/blob/master/lib/App/ecogen.pm6#L9-L22)

The code above now runs but thats because I comment out the `.exitcode` parts and am just relying on the output of stdout (`$content`).

I might suggest you rewrite this:
```
	    my $dl-exit-code = run $CMD, $url, "-O", "gnuplot-5.0.5.tar.gz";
            if not $dl-exit-code == 0 {
                die;
            }
```
to
```
	    my $dl-proc = run $CMD, $url, "-O", "gnuplot-5.0.5.tar.gz";
            if not $dl-proc.exitcode == 0 {
                die;
            }
```
or if you want to try avoiding `.exitcode`
```
	    so run $CMD, $url, "-O", "gnuplot-5.0.5.tar.gz";
            unless "gnuplot-5.0.5.tar.gz".IO.e {
                die;
           }
```

---
...but it might well be that you have to use `:out` and `:err` if its a problem with how stdout/stderr gets piped to parent process. The good news is it can usually be tweaked to work, it's just a lot of trial and error.

**Comment by ugexe** [comment]
```perl6
use Zef::Fetch;
use Zef::Extract;

class Build {
    method build($workdir) {
        if $*DISTRO.is-win {
            die "Sorry, this binding doesn't support windows";
        }
        my $HOME = qq:x/echo \$HOME/.subst(/\s*/,"",:g);
        my $prefix = "$HOME/.p6chart-gnuplot";
        self!install-gnuplot($workdir, $prefix);
    }

    method !install-gnuplot($workdir, $prefix) {
        my $goback = $*CWD;
        chdir($workdir);

        my @fetch-backends = [
            { module => "Zef::Service::Shell::wget" },
            { module => "Zef::Service::Shell::curl" },
        ];
        my $fetcher      = Zef::Fetch.new(:backends(@fetch-backends));
        my $uri          = 'http://ftp.cstug.cz/pub/CTAN/graphics/gnuplot/5.0.5/gnuplot-5.0.5.tar.gz';
        my $archive-file = $uri.IO.basename.IO.e
            ?? $uri.IO.basename.IO
            !! $fetcher.fetch($uri, $uri.IO.basename);

        my @extract-backends = [
            { module => "Zef::Service::Shell::tar" },
            { module => "Zef::Service::Shell::p5tar" },
        ];
        my $extractor   = Zef::Extract.new(:backends(@extract-backends));
        my $extract-dir = $archive-file.IO.basename.subst(/\.tar\.gz/, '').IO.e
            ?? $archive-file.IO.basename.subst(/\.tar\.gz/, '').IO
            !! $extractor.extract($archive-file, $archive-file.IO.basename.subst(/\.tar\.gz/, ''));

        try {
            chdir("extract-dir");
            shell("./configure --prefix=$prefix");
            shell("make");
            shell("make install");
        }
        chdir($goback);
    }
}
```
This works, but you would have to add a `"build-depends" : [ "zef" ]` to your `META6.json`. On the other hand its more portable since it handles wget + curl, and additionally providing an alternative to the `tar` command using perl5 core module. You can probably reverse engineer this so you have no dependencies, just have to find how those modules are spawning/handling those commands differently than the original Build.pm

**Comment by titsuki** [comment]
@ugexe
Thanks for your example!

However, it fails if the download process takes more than 10 minutes, because `Zef::Fetch.fetch` doesn't output any intermediate status to the terminal.
Do you have any ideas for solving this issue?

**Comment by ugexe** [comment]
Hmm, are you sure the download is taking that long and not that its encountering the same deadlock problem as before? I see it happened on OSX only (which hints at the deadlock problem because OSX has a low pipe buffer size).

But maybe you can just try rerunning the test and see if it was a temporary network hiccup.

**Comment by titsuki** [comment]
@ugexe
Thanks for your reply.

> I see it happened on OSX only 

Yes, I only have a problem with OSX.

>  zef can't implement a workaround for all cases - must be fixed in rakudo

I see, I'll wait for an improvement of rakudo.

**Comment by ugexe** [comment]
Can you try this on moar-blead? `rakudobrew nuke moar-blead`, `rakudobrew build moar-blead`

There have been quite a few rakudo improvements in the last week that could possible have resolved this.

**Comment by titsuki** [comment]
Thanks for your advice !
I executed it locally, but it returns error messages that I have never seen before:
```
$ rakudobrew current
Currently running moar-blead-nom
```
```
$ zef --debug build .
===> Building: Chart::Gnuplot
Building with plugin: Zef::Service::Shell::Build+{<anon|78545088>}
Command: /home/itoyota/.rakudobrew/bin/../moar-blead-nom/install/bin/perl6 -Ilib -I. -MBuild -e ::('Build').new.build('/home/itoyota/Programs/p6-Chart-Gnuplot'); exit(0);

# many messages

===> Building [FAIL]: Chart::Gnuplot
Aborting due to build failure: Chart::Gnuplot (use --force-fetch to override)
  in code  at /home/itoyota/.rakudobrew/moar-blead-nom/install/share/perl6/site/sources/41FEBE97057A010AC78876F92FDD03577852170A (Zef::Client) line 329
  in method build at /home/itoyota/.rakudobrew/moar-blead-nom/install/share/perl6/site/sources/41FEBE97057A010AC78876F92FDD03577852170A (Zef::Client) line 294
  in sub MAIN at /home/itoyota/.rakudobrew/moar-blead-nom/install/share/perl6/site/sources/0D8267CB6264C8787F962353AA4E8FE1D57C1E8F (Zef::CLI) line 52
  in block <unit> at /home/itoyota/.rakudobrew/moar-blead-nom/install/share/perl6/site/resources/B53964D4E9DF0E74CD165A0D7947FB8BCF2DDAF6 line 1
```

My code was this state:
https://github.com/titsuki/p6-Chart-Gnuplot/commit/87b2e13e755a6a5bd6d3b7bf5f99545843304758

**Comment by ugexe** [comment]
It builds now for me on OSX, but one of the tests fail (although should be unrelated to zef).

**Comment by titsuki** [comment]
@ugexe
Although I didn't specify `rakudobrew build moar-blead` as a build option (and I'm not sure how to specify it), I also confirmed that zef could fetch `gnuplot-5.0.5.tar.gz` on OSX environment.

I'm very grad to see the success :)
Sorry for my insistence, however, I think that if I handle a more large data (e.g. a dictionary file for morpheme analyzer), it will hang again, because zef is quiet (i.e. print nothing to terminal) during fetching phase. 

Is there any plans to add download progress indicator during that phase so to print some outputs?

**Comment by ugexe** [comment]
So zef used to have something like [this](http://ugexe.com/create-a-perl6-terminal-progress-bar/) but I removed it when I removed concurrency support at the time of Rakudo official first release (too buggy).

I could probably bring something like that back, but maybe some other way is even better. We *might* be able to show how much has been downloaded (since fetcher always saves to a file we can monitor it) but I'm not sure about showing what the total size will be as this may require lots of additional logic for the simple fetcher plugins (and may not even be available for many instances).

The other thing to consider (in regards to presenting this information) is how it will fit in a theoretical output where zef is using concurrency again and could be in multiple phases at once (so maybe a single animated bar like in the blog doesn't make sense here).

So, any suggestions for how a solution's *simplest possible* output might look?

**Comment by titsuki** [comment]
I like apache hive's table form progress indicator: https://medium.com/@anishekagarwal/apache-hive-beeline-progress-bar-fd57c29da65d

This form of indicator will give us sufficient information for confirming the overall progress. 
However, I'm not sure Windows can handle hive like progress table.

**Comment by ugexe** [comment]
I'm going to close this issue but feel free to open a new one with comments/ideas for presenting progress indicators in the CLI
