### ISSUE TITLE
rakudo fails to locate dependencies

### ISSUE THREAD

**Issue by MARTIMM** [ugexe/zef#174]
installing dependency modules seems to fail on Travis with latest perl6 (rakudobrew) and zef
Refs are [BSON on Travis](https://travis-ci.org/MARTIMM/BSON) and [MongoDB on Travis](https://travis-ci.org/MARTIMM/mongo-perl6-driver).

## Context

On travis `zef --depsonly install .` is used to install dependencies. It does not show any problems but when tests are started the tests fail because of missing modules

## Expected Behavior

it should install dependencies before tests are started.

## Actual Behavior

Tests fail because of missing modules

## Steps to Reproduce

both tests are repeated withh --debug. but tests are now failing without verbose errors messages ??

## Your Environment

* This is Rakudo version 2017.05-425-gb0a1b6c built on MoarVM version 2017.05-76-gba6725f
* zef:ver('0.1.16'):auth('github:ugexe')

**Comment by ugexe** [comment]
Have you tried running the tests without zef on a rakudo/moar HEAD like in travis?

**Comment by ugexe** [comment]
Confirmed rakudo bug. Should be fixed in rakudo soon - will update.

**Comment by MARTIMM** [comment]
thanks, i'll wait and see.
FWIW, the tests are not requesting the installations. it is via META6.json

**Comment by ugexe** [comment]
Right, but `depends` (and thus META6.json) do not get to dictate what CompUnit::Repository supplies the dependency. Otherwise `perl6 -I../some-dependency -Ilib -e 'use My::Module::Depending::On::Some::Dependency;'` acts different than if the dependency is installed, or used via Third::Party::CUR::Foo or Third::Party::CUR::Bar. The choice of repo source is for the end user to decide, not module authors.

**Comment by ugexe** [comment]
This should be fixed with `rakudobrew build moar-blead` (dunno if `rakudobrew build moar` will be enough or not).

**Comment by MARTIMM** [comment]
did travis tests again and all went fine, so I'll close it now.
