### ISSUE TITLE
Failing to update repo mirror on windows

### ISSUE THREAD

**Issue by ultra-gitsome** [ugexe/zef#178]
I have been googling configuration info for zef....and it is pretty thin. My install is failing to find the cpan or git repositories. That seems like a basic check/test during the install of zef would have a lot of value - because until I figure out how to point zef at a remote repository, it is mostly useless.

## Context
zef  -v --cpan --metacpan search URI
Failed to update cpan mirror No such method 'IO' for invocant of type 'Any'
Failed to update cpan mirror Failed to open file C:\Users\WinUser\.zef\store\cpan.json: no such file or directory
Failed to update cpan mirror No such method 'IO' for invocant of type 'Any'
Failed to update cpan mirror Failed to open file C:\Users\WinUser\.zef\store\cpan.json: no such file or directory
^CTerminate batch job (Y/N)? y

## Expected Behavior
1) Finds mirror site, or
2) Provides an option to add mirrors, or
3) Suggests mods to configuration files

## Actual Behavior
Finds nothing

## Steps to Reproduce
Dated ACER laptop
Win 7 home OS
rakudo 2017.04  

## Your Environment
* perl6 -v
perl6 -v
This is Rakudo version 2017.04.3 built on MoarVM version 2017.04-53-g66c6dda
implementing Perl 6.c.

* perl6 -e 'say $*VM.config<os>'
 perl6 -e 'say $*VM.config<os>'
The system cannot find the file specified.

**Comment by ugexe** [comment]
zef already has tests for repositories in `xt/`, and they (along with various real world tests) are run on both travis-ci (linux/osx) and appveyor (windows). They are in `xt/` because zef is not a tool just for remote installation.

If `perl6 -e 'say $*VM.config'` gives you 'The system cannot find the file specified' your rakudo installation may be broken. If that command *does* work we can move to the next step: what version of zef is being used? (`zef --/cached --/p6c --/cpan --/metacpan info zef`)

**Comment by ugexe** [comment]
If you can reinstall zef (clone repo into new directory, cd into repo, `perl6 -Ilib bin/zef uninstall zef`, `perl6 -Ilib bin/zef install .`) you'll get better error messages that show the url of the mirrors that are failing. It's also possible your problem is fixed in a newer version.

The mirrors can only be set in the configuration file at the moment - see: https://github.com/ugexe/zef/blob/master/resources/config.json#L39

If you just want to mess around you can do `zef --help` and it will show you the path of the configuration file you can edit to get the changes to take effect (the name of this file depends on where its stored - it might be a hash, it might be config.json).

**Comment by ultra-gitsome** [comment]
Sorry about the slow response. I have been fiddling with other Perl6 code and that has absorbed most of coding time.

I have version 0.1.11 of zef installed. At the moment, I am bypassing the mirrors and maintaining github local repositories of the modules that I use. I'm then using zef to install the local repo's into rakudo. At some point I will need a new clean install of rakudo and zef, so then I will get zef properly configured.
