### ISSUE TITLE
Zef installation on Ubuntu not working on 2015.11

### ISSUE THREAD

**Issue by Alcatros** [ugexe/zef#196]
## Context
I'm using Ubuntu 16.04 and tried for the first time to install perl6 and as a consequence zef in order to fetch modules. This didn't work as described.

## Expected Behavior
Installation of zef completes

## Actual Behavior

Following error is thrown;

alcatros@alcatros-VirtualBox:~/perl6project/zef$ perl6 -I. bin/zef install .
===SORRY!=== Error while compiling /home/alcatros/perl6project/zef/lib/Zef.pm6
Undeclared names:
    JSONException used at line 16
    Supplier used at lines 36, 37

## Steps to Reproduce
$ git clone https://github.com/ugexe/zef.git
$ cd zef
$ perl6 -I. bin/zef install .
## Your Environment
As i can't run zef yet;
Env;Linux alcatros-VirtualBox 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Perl version; This is perl6 version 2015.11 built on MoarVM version 2015.11

**Comment by tony-o** [comment]
What's the output of: perl6 -Ilib bin/zef install .

--
tony.odell@live.com

On August 4, 2017 at 18:35:51, Alcatros (notifications@github.com<mailto:notifications@github.com>) wrote:

Context

I'm using Ubuntu 16.04 and tried for the first time to install perl6 and as a consequence zef in order to fetch modules. This didn't work as described.

Expected Behavior

Installation of zef completes

Actual Behavior

Following error is thrown;

alcatros@alcatros-VirtualBox:~/perl6project/zef$ perl6 -I. bin/zef install .
===SORRY!=== Error while compiling /home/alcatros/perl6project/zef/lib/Zef.pm6
Undeclared names:
JSONException used at line 16
Supplier used at lines 36, 37

Steps to Reproduce

$ git clone https://github.com/ugexe/zef.git
$ cd zef
$ perl6 -I. bin/zef install .

Your Environment

As i can't run zef yet;
Env;Linux alcatros-VirtualBox 4.8.0-36-generic #36<https://github.com/ugexe/zef/pull/36>~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Perl version; This is perl6 version 2015.11 built on MoarVM version 2015.11

**Comment by Alcatros** [comment]
alcatros@alcatros-VirtualBox:~/perl6project/zef$ perl6 -Ilib bin/zef install . 
===SORRY!=== Error while compiling /home/alcatros/perl6project/zef/lib/Zef.pm6
Undeclared names:
    JSONException used at line 16
    Supplier used at lines 36, 37

**Comment by tony-o** [comment]
Can you update perl6?  2015.11 is pretty badly outdated.

--
tony.odell@live.com

On August 4, 2017 at 19:51:13, Alcatros (notifications@github.com<mailto:notifications@github.com>) wrote:

alcatros@alcatros-VirtualBox:~/perl6project/zef$ perl6 -Ilib bin/zef install .
===SORRY!=== Error while compiling /home/alcatros/perl6project/zef/lib/Zef.pm6
Undeclared names:
JSONException used at line 16
Supplier used at lines 36, 37

**Comment by Alcatros** [comment]
That's the current one which ships with Ubuntu :/ i would need to build it from scratch ,is that really necessary? If so it would mean Ubuntu comes today with a garbage perl version (which should be removed in my opinion, just creates unnecessary hassle) Thanks for your help

**Comment by ugexe** [comment]
The first official release was 2015.12

**Comment by Alcatros** [comment]
Thanks for the help, i will get another version

**Comment by Alcatros** [comment]
Ill check if i can file this as bug, there should be no pre-release version in ubuntu, once perl6 becomes more mainstream there will be many people having the same issue

**Comment by ugexe** [comment]
Thanks
