### ISSUE TITLE
Add 'init' option for creating META6.json

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#219]
Since this is becoming a general package manager for perl6, it would be nice to have an option to create a sensible META6.json from scratch

## Context

Have
 
    zef init

create a META6.json if it does not exist

## Expected Behavior

It creates a META6.json using known data and placeholders where there is not

## Actual Behavior

it does not exist right not.

## Steps to Reproduce

Does not apply

**Comment by ugexe** [comment]
See http://github.com/ugexe/zef/issues/132

**Comment by JJ** [comment]
It's not exactly the same. This one generates a META6.json, it does not generate scaffolding for a new module the way mi6 does. `zef` is also a (kind-of) core app, you don't need to use an external tool such as mi6. Besides, the way it's programmed it would use defaults, and more could be added by reading from zef config. 
Anyway, it's your call, obviously. Since I was on my way of creating a plugin, I did this as an exercise to get acquainted with the internals. What do you suggest?

**Comment by ugexe** [comment]
Consider first (run from a directory with a META6.json):
`perl6 -e 'say Distribution::Path.new($*CWD).meta'`

while this relies on the presence of a META6.json file there is no reason why it has to. If it were to guess much of this data the logic is just:

```
class Zef::Distribution::FileSystem does Distribution::Locally does Zef::Distribution {
    has %!meta-cache;

    my sub from-json($str) { Rakudo::Internals::JSON.from-json($str) }

    method meta {
        %!meta-cache ||= do {
            my $meta-path = $.prefix.child('META6.json');
            die "No META6 data found at {$.prefix}." unless $meta-path.e;
            my $orig-meta-data = try from-json($meta-path.slurp);
            die "META6 data invalid at {$meta-path.absolute}" unless $orig-meta-data;

            my %meta-data = $orig-meta-data.hash andthen {
                with depspec-hash($_) { .{$^a.keys} = $^a.values }                                   # normalize meta data
                resources-to-files(|$_.<resources>).map: { .<files>{$^a.key} = $^a.value }           # populate `files` field with resources/
                list-paths($.prefix.child('bin')).map: { .<files>{$^a} = $^a.IO.relative($.prefix) } # populate `files` field with bin/
            }
            %meta-data;
        }
    }
}
```

so this theoretical code works without the presence of a META6.json:
`perl6 -e 'say Zef::Distribution::FileSystem.new($*CWD).meta'`

---

Why is this important when you just want to write a meta file to disk? Because there is already something responsible for reading/writing a META6.json file to disk: CompUnit::Repository::*. Consider CompUnit::Repository::Installation (CURI) and CompUnit::Repository::FileSystem (CURFS). `CURI.install($dist)` takes a Distribution and writes it to the sha1 file names we all know and love, and it also reads from this format. `CURFS.install($dist)` *does not exist* but it -could-, even if that is just using `augment` to add a `method install($from, $to) { $from.IO.copy($to.IO) }`. BUT! CURFS is what is responsible for `-Ilib` or `use lib <lib>` (not to be confused with `-I.` if META6.json exists), so it must know how to read a distribution that lacks a META6.json file. The logic for that exists in CURFS but, as i've shown, it needs to be moved within a `Distribution` implementation (that CURFS would still use) to expose this api (and indeed this work is done in https://github.com/rakudo/rakudo/pull/1132 although I have to revist).

In other words: for meta6 and package file data - `Distribution` implementations are for serializing, `CompUnit::Repository` are for deserializing.

So from the `Zef::CLI` angle this theoretically ends up something like:
`perl6 -e 'CompUnit::Repository::FileSystem.new($*CWD).install: Zef::Distribution::FileSystem.new($*CWD)'`

Which means `Zef::CLI` does not need to know about implementation details like checking a .git folder or if the json it outputs is understandable to rakudo's json parser (nor does it technically need to know anything about json). These details are handled by `Distribution` interfaces... `Distribution::Git::Local` for instance would be something that knows how to parse a git repo saved to a local disk ([example](https://github.com/ugexe/Perl6-Distribution--Common/blob/master/lib/Distribution/IO/Proc/Git.pm6)) including git specific error handling (otherwise git, tar, path, etc would each need protocol specific code throughout the codebase). Everything will -just work- (hopefully!) because it is using all the same pieces used to read/install any other distribution.

---

I know this is a wall of text, but I wanted to explain the decoupling strategy that is used. Implementing a robust form of `zef init` on top of this should be rather simple once familiar with CompUnit::Repository/Distribution, but I'm afraid despite being one of the most familiar that I'm not the best explainer.

**Comment by JJ** [comment]
No, it's great. Thanks!
