### ISSUE TITLE
Failed to find a META6.json file -- failure is likely

### ISSUE THREAD

**Issue by stmuk** [ugexe/zef#225]
Can't reliably reproduce but installing Task::Galaxy shows warnings/errors like

```
===> Extraction [OK]: SCGI to /home/steve/.zef/store/SCGI.git
Failed to find a META6.json file -- failure is likely
  in block  at /home/steve/.rakudobrew/moar-blead-master/install/share/perl6/sit
e/sources/9062A39D0256C0BD797016C3FE93D839191AFE2B (Zef::Client) line 262
===> Extraction [OK]: Email::Simple to /home/steve/.zef/store/p6-Email-Simple.git
Use of uninitialized value $meta6-prefix of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something m
eaningful.
  in block  at /home/steve/.rakudobrew/moar-blead-master/install/share/perl6/sit
e/sources/9062A39D0256C0BD797016C3FE93D839191AFE2B (Zef::Client) line 291
===> Extraction [OK]: HTTP::UserAgent to /home/steve/.zef/store/http-useragent.git
```

**Comment by ugexe** [comment]
Email::Simple still uses a META.info file. We’ve been trying to move people away from them for awhile. Looks like it is an abandoned project since PR to fix it has been open for 9 months.

**Comment by stmuk** [comment]
Ah I'd misread the log and checked SCGI. The log might be clearer if the warning included the target module
eg. something similar to  "Failed to find a META6.json for Email::Simple" 

or maybe "-v" (which I used) could print out which module is being processed at its start and end?

**Comment by ugexe** [comment]
Yes an indicator will help. Added in 377dd649afded1c86124302c08f252dcc0d056d9

There is a `--debug` flag which would give you a `===> Extracting: Email::Simple` (as well as for fetching, etc). It is not a verbose flag because if you consider a parallelized installer it wouldn't mean much relative to the output above or below it (assuming a boring CLI interface e.g. no ncurses). So generally looking to have the output make sense on a line-by-line level (e.g. adding the name of the module missing a META6.json) for more typical usage.

**Comment by stmuk** [comment]
Thanks!
