### ISSUE TITLE
Allow `--force` options in `zef upgrade`

### ISSUE THREAD

**Issue by zoffixznet** [ugexe/zef#231]
Would be handy if you could specify `--force` with `zef upgrade`. Currently, it just tells me all modules are at their latest versions, but it's not uncommon in our p6c ecosystem for authors to commit patches or even new features, yet never bump the version number.

Without `--force` those updates aren't fetched.

## Your Environment
```
$ perl6 -v
This is Rakudo version 2018.01-203-g0d0fe79 built on MoarVM version 2018.01-89-ga01cdb4
implementing Perl 6.c.
$ zef info zef
- Info for: zef
- Identity: zef:ver<0.2.2>:auth<github:ugexe>

```

**Comment by ugexe** [comment]
It is currently possible to do something like:
```
zef uninstall Foo::Bar
zef nuke StoreDir
zef install Foo::Bar --force-install --/cached
```
There are ramifications to allowing the user to install conflicting modules on their system, and making it easier is not something I'm particularly fond of doing. Either A) every distribution would have to be downloaded every query to determine if the author updated but forgot to bump their version or B) all sorts of complex plumbing for various backends to determine remote changes in data. CUR can get away with using sha hashes because it has fast access to the file data -- something zef has no guarantee of. Basically we want to calculate certain guarantees at resolve phase, not after fetch phase. This design has many advantages, but it does not fit the particular case of mutable versions too well.

Now perhaps someone can make a case as to why enabling this behavior is overall beneficial. But it would not be for `zef upgrade ...` as I would *like* `upgrade` to have a specific, expected, reproducible meaning. Maybe e.g. `zef sync ..` / `zef resync ...` which would need to handle cleaning up conflicts in the local cache as well as installations.

**Comment by zoffixznet** [comment]
Ah, OK, I forgot multiple module versions could be installed.
