### ISSUE TITLE
Incorrect treatment of %*ENV<PERL6LIB> when relative paths are used

### ISSUE THREAD

**Issue by AlexDaniel** [ugexe/zef#271]
Code in question:
https://github.com/ugexe/zef/blob/846c5ab92cdf6a788abc23b19ce81979b84d8e4a/lib/Zef/Service/Shell/prove.pm6#L31-L41

Basically, PERL6LIB can have a list of paths to insts. However, on line 41 it runs the process in a different `:cwd`. This means that relative paths in PERL6LIB are no longer pointing at the right locations.

It causes this:
* Imagine module Y depends on X, and we run `zef install Y`.
* Zef thinks that dependency `X` is installed, because a path to the right inst is provided in PERL6LIB.
* Therefore Zef does not attempt to install X.
* Then it goes to run `prove` for the module Y, and all tests fail because module X is not found.

I haven't trying debugging Zef's code so my understanding could be wrong, but slapping `.absolute` on paths in my code made Zef install stuff properly (successfully running the tests in prove).

**Comment by ugexe** [comment]
Using relative paths in PERL6LIB is already a recipe for disaster and why you never see me tell people to use PERL6LIB=. or PERL6LIB=lib

Using .absolute just makes the breakage caused by following this pattern less consistent. A more appropriate solution would be to determine these paths from $*REPO (which will already have absolutified the various paths before any chdir could cause issues).

**Comment by ugexe** [comment]
On second thought there is nothing for zef to do here since zef should not be mutating the items of PERL6LIB ( you can't just slap on .absolute to arbitrary specs like`GitHub#user<ugexe>#repo<Perl6-PathTools>#branch<master>#/` ).
