### ISSUE TITLE
zef documentation is in Pod (perl 5) format.

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#283]
## Context

Readme.pod is written in Perl 5 pod. It fails with:

```
perl6 --doc README.pod 
===SORRY!=== Error while compiling /home/jmerelo/Code/forks/perl6/zef/README.pod
Preceding context expects a term, but found infix = instead.
Did you make a mistake in Pod syntax?
at /home/jmerelo/Code/forks/perl6/zef/README.pod:9
------> =for ⏏HTML <a href="https://travis-ci.org/ugexe
```

in Perl 6.

## Expected Behavior

Documentation of a module is an important, and integral part of it; clients should be expected to have the minimum amount of tools in order to use it. Perl 6 users, in general, need not be assumed to have perl + perldoc (a separate installation in some operating systems). As a matter of fact, modules.perl6.org does not automatically display pod, just Markdown, as can be seen with Bailador (displayed: https://modules.perl6.org/dist/Bailador:cpan:UFOBAT) vs zef (omitted: https://modules.perl6.org/dist/zef:cpan:UGEXE).

The expected behavior would be, thus, use either a format for the README that can be interpreted by the Perl6 ecosystem or one that can be interpreted by Perl6 itself.

## Actual Behavior

It's written in Perl Pod.

## Steps to Reproduce

It's the current state of the repo at commit 9cb53c84ba9808fa2b96bcb80b2b16cd0e56aea1

**Comment by ugexe** [comment]
github doesn't render Pod6, so that is not an option. Changing from a `README.pod` to `README.md` just because one ecosystem doesn't have the one or two lines of code to parse it, breaking all current links pointing at the `README.pod`, or because p6doc doesn't want to add logic for parsing regular pod (the fact it tries to read a README is already flawed), doesn't seem like a good compromise.

One day github might render Pod6. At that time we can reconsider if changing the README format is worth losing backlinks. However I imagine documentation will eventually be written inside the .pm6 files themselves, and that the format of the README will be irrelevant (as it should be).
