### ISSUE TITLE
Breaking changes in distro index location

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#289]
The *old* location of the ecosystem apparently still work:

```
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
```

But zef now looks for distros in the new files, which, for the time being, seem to have the same content as the old files.

```
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
```

That means that old versions of zef, even if they work correctly, might no longer find or download the distros that have been updated since the change if, for some reason, the old indices stop being updated. This is going to break, for instance, all docker containers with old versions of zef that relied on that location, or for that matter all old installations that otherwise work perfectly.

## Expected Behavior

This change (or duplication) of location should have been either discussed with the community or, at least, announced. It's a major change that automatically makes all installations older than the change obsolete, or at least unable to access any new distros.
Apparently, the old indices are still updated at the same time as the new ones. Still, since this is not documented something could break in the future.

**Comment by ugexe** [comment]
It is not a breaking change -- it is the opposite of a breaking change. There is a new url so that old versions of zef would not choke. Regardless this is not something that requires documentation as it is an implementation detail, and if someone really must know they can put in some effort and look at the git history or git blame to find https://github.com/ugexe/zef/commit/d195edc7e0678c3a5d5a063b85eb5b9ddb7b6efe
