### ISSUE TITLE
Should zef uninstall accept a path?

### ISSUE THREAD

**Issue by frithnanth** [ugexe/zef#314]
## Context
This is a feature request, not an issue.

## The problem
During a module developing cycle I use a git pre-push hook. So far my pre-push script is just:

`zef install . --force-install`

but now I'm thinking that it's not enough and I'd like to uninstall the current module and then re-install it.
To avoid having to edit manually each pre-push script, I need a way to uninstall an "anonymous" module, something along the lines of `zef uninstall .`.

**Comment by ugexe** [comment]
You can’t uninstall a module via a path because the path might point to something with the same version but had the file contents change (so no longer technically the version that would have been installed earlier).

Additionally it does not read well and is ambiguous— uninstall the current path? In reality its asking “open the META6 for that path and use the name/version from that to uninstall”.

The distribution to be uninstalled is supposed to come from the repository it will be removed from, not from a non repository path source.

Is there any package management tool that when giving uninstall a path it actually uninstalls the distribution from somewhere completely different?

**Comment by niner** [comment]
You can easily do the same by running `zef uninstall $(perl6 -e 'use JSON::Fast; my $meta = from-json slurp "META6.json"; say "$meta<name>:auth<$meta<auth>>:ver<$meta<version>>"')`

**Comment by frithnanth** [comment]
@niner sure.
I thought that since zef is able to read what's inside the META, because it does that when installing a module, maybe it could do it even when uninstalling.

**Comment by frithnanth** [comment]
I'm retracting this because I came to think it's a bad idea: when one pushes a release usually one has changed the `version` tag in their META6.json, so `zef uninstall .` should uninstall **all** previous versions of the module.
While this is what I do, might not be what everyone else wants.
