### ISSUE TITLE
 /usr/bin/env: ‘perl6\r’: No such file or directory

### ISSUE THREAD

**Issue by chenjianxin** [ugexe/zef#324]
perl6 -v
This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.

 perl6 -I. bin/zef install .
===> Testing: zef:ver<0.7.4>:auth<github:ugexe>:api<0>
===> Testing [OK] for zef:ver<0.7.4>:auth<github:ugexe>:api<0>
===> Installing: zef:ver<0.7.4>:auth<github:ugexe>:api<0>

1 bin/ script [zef] installed to:
/home/elecbuggy/rakudo/install/share/perl6/site/bin

**zef list --installed
/usr/bin/env: ‘perl6\r’: No such file or directory**

**zef install --/test cro
/usr/bin/env: ‘perl6\r’: No such file or directory**

**Comment by ugexe** [comment]
Are you sure ‘zef’ command / PATH is pointing to the location it told you to install to?

**Comment by chenjianxin** [comment]
> 
> 
> Are you sure ‘zef’ command / PATH is pointing to the location it told you to install to?

yes !

echo $PATH
/....(ignored)../home/elecbuggy/rakudo:/home/elecbuggy/rakudo/install/share/perl6/site/bin

**Comment by ugexe** [comment]
I'm guessing its a rakudo bug because rakudo (not zef) [creates the shebang line](https://github.com/rakudo/rakudo/blob/e45bb3418d5f3964907739e916e95078e6e09995/src/core.c/CompUnit/Repository/Installation.pm6#L53-L56) shown earlier

Does `perl6 /home/elecbuggy/rakudo/install/share/perl6/site/bin/zef` work?

Does `perl6 -MZef::CLI -e '' list --installed` work? What is the output?

Does `perl6 -e 'say run("perl6", "-v", :out).out.slurp'` work?

If all the above work then I'm not sure what is happening.

**Comment by chenjianxin** [comment]
oh!!!!  I got it  

because my wsl2 PATH contain my windows PATH 
both have the perl6 and zef path  so they conflict

I remove the part of windows PATH form wsl2 PATH then it work!
