### ISSUE TITLE
Windows: Zef fails to install modules if Rakudo installed in a directory that has a space.

### ISSUE THREAD

**Issue by hankache** [ugexe/zef#337]
If Rakudo is installed under some directory that doesn't contain a space in its name (C:\rakudo), Zef works correctly.
If it's installed under a directory that has a space (C:\Program Files\rakudo), Zef fails to install modules.

Windows 10 - Rakudo 2020.02
```
C:\Users\naoum>zef install Linenoise -v
===> Searching for: Linenoise
===> Found: Linenoise:ver<0.1.1>:auth<Rob Hoelz> [via Zef::Repository::LocalCache]
===> Building: Linenoise:ver<0.1.1>:auth<Rob Hoelz>
[Linenoise] Command: C:\Program Files\rakudo\bin\perl6.exe -e require 'C:\Users\naoum\.zef\store\p6-linenoise.git\4b98fe19b999a6da63f7427ab77f22e78739af88\Build.pm6'; ::('Build').new.build('C:\Users\naoum\.zef\store\p6-linenoise.git\4b98fe19b999a6da63f7427ab77f22e78739af88') ?? exit(0) !! exit(1);
[Linenoise] 'C:\Program' is not recognized as an internal or external command,
[Linenoise] operable program or batch file.
===> Building [FAIL]: Linenoise:ver<0.1.1>:auth<Rob Hoelz>
Aborting due to build failure: Linenoise:ver<0.1.1>:auth<Rob Hoelz> (use --force-build to override)
```

**Comment by ugexe** [comment]
```
[Linenoise] Command: C:\Program Files\rakudo\bin\perl6.exe -e require 'C:\Users\naoum\.zef\store\p6-linenoise.git\4b98fe19b999a6da63f7427ab77f22e78739af88\Build.pm6'; ::('Build').new.build('C:\Users\naoum\.zef\store\p6-linenoise.git\4b98fe19b999a6da63f7427ab77f22e78739af88') ?? exit(0) !! exit(1);
[Linenoise] 'C:\Program' is not recognized as an internal or external command,
```
If the language itself is cannot handling running a path that itself generates (`run($*EXECUTABLE, ...`) how exactly should it be handled by anything using that language?

**Comment by hankache** [comment]
````
C:\Users\naoum>perl6 -e "say $*EXECUTABLE"
"C:\Program Files\rakudo\bin\perl6.exe".IO

C:\Users\naoum>perl6 -e "run($*EXECUTABLE,'-e say 1')"
1
````

**Comment by ugexe** [comment]
It’s a simplified example, but you are welcome to spend a minute or two to look at how zef makes the same call

**Comment by ugexe** [comment]
Please try poking here -- https://github.com/ugexe/zef/blob/e77560688e6a5508b476bd9dba013523aa695b15/lib/Zef.pm6#L4

For instance you might try removing the `cmd.exe` and the `/x/d/c`, although without that I *think* other things will fail. Maybe whatever problem that originally worked around is fixed now... it should be pretty obvious if anything breaks.

**Comment by hankache** [comment]
@ugexe do you believe this is related to https://github.com/Raku/problem-solving/issues/20 ?

**Comment by ugexe** [comment]
Yes.

It might also be that zef should not be prefixing commands to run with `cmd.exe /x/d/c` (even if the fix in that problem solving link would theoretically fix zef as-is), although without doing that I suspect certain commands/scripts might not launch or be available... and I don't remember which ones those would have been.

**Comment by patrickbkr** [comment]
_>>>>> Preface_

Before I started working on relocatability the main rakudo executable was a bat file on Windows. The rakudo compilation process needs to call itself and failed in situations such as spaces in the path because it's not reliably possible to pass arbitrary arguments to bat files (the path to the bat file is also an argument to cmd.exe). The only solution I found (after a lot of digging in) was to replace the rakudo bat files with native executables. I still don't entirely understand how one should call bat files correctly, but my current belief is, that it's not possible pass arguments with spaces in them unchanged cmd.

The changes I persue in Raku/problem-solving#20 try to solve the inability to exactly control what arguments are passed to processes that do not conform to the quasi-convention of argument quoting on Windows. cmd.exe is one of those non conforming programs. But even when having full control over the arguments, cmd.exe still makes it very hard (I think even impossible) to pass certain strings as arguments.

_<<<<< End of Preface_ 

I suspect that the `cmd.exe /x/d/c` thing is a (I suspect non perfect) workaround for those same problems in zef (`zrun` is at least once used to call `$*EXECUTABLE`). I'm unsure whether there are other places in zef that use `zrun` to call bat files. If yes, then those places might need special handling to make them work reliably and might depend on the problem-solving#20 ticket. If not, then I think the `cmd.exe /x/d/c` thing is not necessary and can just be removed.

**Comment by patrickbkr** [comment]
I am currently looking into this. Of all the places that use `zrun()` only `prove` turns out to be a `.bat` file on Windows. I can special case that occurrence.

But there are several places where `$*EXECUTABLE` is called. That *is* a `.bat` file on older Rakudo releases. I'm unsure on how to deal with that.
I could either:
- Ignore it. That would cause zef to fail on older Rakudo releases when Rakudo is located in a folder with spaces in it.
- Try to detect this situation (e.g. by looking for the `.bat` suffix or checking the Rakudo version) and quote appropriately in those situations. I could also do that centrally in the `zrun` implementation.

@ugexe What's your opinion?

**Comment by ugexe** [comment]
I'm ok with ignoring the failure on older rakudo releases. I'm not against detecting the situation either, but I'm not sure if its worth the effort given the small subset of users it would help (uses Windows, is on old rakudo, but also manually updating zef...?)
