### ISSUE TITLE
zef looks fails on https://modules.raku.org/dist/Hash::MultiValue:cpan:HANENKAMP

### ISSUE THREAD

**Issue by melezhik** [ugexe/zef#348]
Hi Nick. It's not critical, just a question why is thisso?
```shell
zef look https://modules.raku.org/dist/Hash::MultiValue:cpan:HANENKAMP
===> Searching for: https://modules.raku.org/dist/Hash::MultiValue:cpan:HANENKAMP
Failed to resolve any candidates. No reason to proceed
```

This would allow people to run RakuDist builds using `https://modules.raku.org/dist/$module:cpan:$author` format.

also see https://www.reddit.com/r/rakulang/comments/gfvheo/rakudist_update_long_queue_short/fpw63dp?utm_source=share&utm_medium=web2x

**Comment by melezhik** [comment]
if you need a build log it's here - http://repo.westus.cloudapp.azure.com/sparky/report/debian/499

**Comment by ugexe** [comment]
https://modules.raku.org/dist/Hash::MultiValue:cpan:HANENKAMP is not an identity, so it should not work. `Hash::MultiValue` is an identity. `./MyFolder` is an identity. `https://github.com/zostay/p6-Hash-MultiValue.git` is an identity (which coincidentally doesn't work with `zef look`). This is the core functionality needed to build any project. Giving certain urls special logic is outside of providing core functionality, along with knowing how to map non-url compatible values to such urls -- nothing is stopping some external plugin and config change from doing these things though.

**Comment by melezhik** [comment]
thanks for clarification Nick. this was my assumption. cc @raiph

**Comment by melezhik** [comment]
cc @AlexDaniel

**Comment by AlexDaniel** [comment]
@ugexe what about these?

* `Foo::<b>Foo`
* `* Foo:: *`

IIRC zef is happy to install these modules locally (with `zef install .`) but asking zef to install them from the ecosystem doesn't work:
```
$ zef install '* Foo:: *'
===> Searching for: * Foo:: *
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
No candidates found matching identity: * Foo:: *
$ zef install 'Foo::<b>Foo'
Don't understand identity: Foo::<b>Foo
```

**Comment by ugexe** [comment]
I mean its a question of how much complexity is it worth to allow such edge case silly scenarios. Should someone be able to name their distribution "https://github.com/ugexe/zef.git" and thus hijack the zef install instructions? There is a [URI grammar](https://github.com/ugexe/zef/blob/master/lib/Zef/Utils/URI.pm6), so its easy to break down that identity. Paths aren't so simple... at one time I tried to make the URI grammar work with `file://` but I forget how that turned out (nor do I think anyone would want to start doing `zef install file://.`), and thus anything starting with a dot is always a path. Lastly we try to break down a raku identity from a string, but the core does not provide a way to do this and thus we have to figure out the short-name ver auth api (any other potential attribute) with an [ad-hoc grammar](https://github.com/ugexe/zef/blob/0414984b70c401114e3e84c48cc7d342c8af3d83/lib/Zef/Identity.pm6#L13-L30) -- its not a 1-to-1 mapping with raku nor can it ever be since `zef:ver(EVAL { ... })` should never be allowed. If someone thinks they can come up with a better grammar for parsing raku identities from strings that can handle more edge case scenarios, doesn't use EVAL, isn't significantly slower, and isn't significantly more complex then it would be a welcome addition.

**Comment by AlexDaniel** [comment]
@ugexe but then shouldn't zef refuse to install them? That is, if I run `zef install .` all these modules with weird names install just fine, and `zef list --installed` lists them:
```bash
$ zef list --installed
===> Found via /home/alex/.rakudobrew/versions/moar-master/install/share/perl6/site
 * Foo:: * :ver<0.0.1>:auth<github:AlexDaniel>:api<1>
--Foo::--Foo:ver<0.0.1>:auth<github:AlexDaniel>:api<1>
```

**Comment by ugexe** [comment]
Just because the recommendation manager doesn't know how to handle those names yet doesn't mean you shouldn't be able to install them with a little extra effort if you know what you're doing. And it is so edge case its not worth adding in warnings because that would require improving the grammar to know when it has misparsed (and of course if it was that smart it could just correctly parse the name for the recommendation manager to begin with).
