### ISSUE TITLE
Zef uninstall distribution identity match bug

### ISSUE THREAD

**Issue by bazzaar** [ugexe/zef#379]
## Context
Given two installed distributions : 
File::Find:ver<0.1>
File::Find:ver<0.1.1>

the command : 
zef uninstall "File::Find:ver<0.1>"

results in : 
===> Uninstalled from /home/bazzaar/.raku
File::Find:ver<0.1>
File::Find:ver<0.1.1>

## Expected Behavior
File::Find:ver<0.1.1> should not have been uninstalled

## Your Environment
bazzaar@localhost:~> raku -v
Welcome to Rakudo(tm) v2020.12.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12.

bazzaar@localhost:~> zef list --installed
===> Found via /home/bazzaar/.raku
...
Encode:ver<0.0.3>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Ignore:ver<1.1>:auth<Jonathan Worthington <jnthn@jnthn.net>>
File::Temp:ver<0.0.8>
File::Which:ver<1.0.1>
GTK::Simple:ver<0.1.13>
...
zef:ver<0.9.4>:auth<github:ugexe>:api<0>
===> Found via /opt/rakudo-pkg/share/perl6/core
CORE:ver<6.d>:auth<perl>
zef:ver<0.9.4>:auth<github:ugexe>:api<0>

**Comment by ugexe** [comment]
Looks like it is caused by https://github.com/ugexe/zef/commit/3ebeb1927b928c80cf8c2d03a314e50c5af8c0b6#diff-99ec689f9f6d18659b89af77229144ccc15550a58cb143ab461765f2dd26b5bb

**Comment by bazzaar** [comment]
ugexe, thank you for looking at this issue : )
I'm not sure I fully understand the changes, so please forgive me if I misunderstand. Does the search string the user provided now get padded out to match a more fully qualified version number of an installed distribution (ie. user provides v1.1, which would then match installed v1.1.0)? If so, I'm wondering why it is ever necessary to modify the user provided search string, if a wildcard is not used? Would it be possible for both v1.1 and v1.1.0 to have been installed over a lengthy period, and it is this that the user might be trying to fix with the zef uninstall command.

**Comment by ugexe** [comment]
I actually think its a rakudo bug. I fixed a similar issue in the core here -- https://github.com/rakudo/rakudo/commit/01dbd874ee5f23fdb3351d2bce1b9af7629caea0 -- which is why I removed the zef code linked earlier. However I overlooked that a similar change would be needed if the RHS of the smart match was longer. Observe:

```
raku -e 'say v0.1 ~~ v0.1.1; say v0.1.0 ~~ v0.1.1; say v0.1.1 ~~ v0.1; say v0.1.1 ~~ v0.1.0'
False
False
True
False
```

imo the output above should be only `False`. To get that behavior one can modify rakudo as such:

```
diff --git a/src/core.c/Version.pm6 b/src/core.c/Version.pm6
index 63513240d..34f2574f7 100644
--- a/src/core.c/Version.pm6
+++ b/src/core.c/Version.pm6
@@ -177,7 +177,7 @@ augment class Version {
         my int $i = -1;
         while nqp::islt_i(++$i,$max-elems) {
             my $v := nqp::isge_i($i,$elems)
-              ?? Whatever
+              ?? 0
               !! nqp::atpos($!parts,$i);

             # if whatever here, no more check this iteration
```

however the above patch results in a failure of a single spec test -- https://github.com/Raku/roast/blame/981c8c1ad4b6d7728b710f29ba3d063199f656d8/S02-literals/version.t#L24 -- although I'm not sure that test is correct.

---

As for what this zef code does is that it pads the shorter of two versions being compared with `0`, which is what the rakudo diff above does. With that change `File::Find:ver<0.1>` will no longer match `File::Find:ver<0.1.1>` (although it would, and indeed already did/does, match `File::Find:ver<0.1.0>` in both zef and raku -- `raku -e 'use Test:ver<6.d.0>'`). Normalization can only happen in the context of version comparison since there needs to be two versions (and thus there is no way to normalize for raku installation).

> Would it be possible for both v1.1 and v1.1.0 to have been installed over a lengthy period

I think technically you could install such distributions into raku, although I *think* trying to do it with zef would result in it telling you its already installed (because raku just does a lookup on the sha1 of the long name, which is different for e.g. `Test:ver<0.1>` and `Test:ver<0.1.0>`, whereas zef does a slower lookup doing actual meta data version comparisons).

**Comment by niner** [comment]
> however the above patch results in a failure of a single spec test --
> https://github.com/Raku/roast/blame/981c8c1ad4b6d7728b710f29ba3d063199f656d
> 8/S02-literals/version.t#L24 -- although I'm not sure that test is correct.

I think the test is correct and the behavior is entirely intentional. It's 
just meant to cover a different use case.

The test ensures that you can say "I need a major version 1" and any minor 
version will match, as long as the major version is the same. The major use 
case for smart matching versions is when requiring a module with a version 
specifier. This is also where we find it in the design documents:

"Saying 1.2.1 specifies an exact match *on that part* of the version number, 
not a minimum match. To match more than one version, put a range operator as a 
selector in parens:

    use Dog:ver(v1.2.1..v1.2.3);
    use Dog:ver(v1.2.1..^v1.3);
    use Dog:ver(v1.2.1..*);
When specifying the version of your own module, 1.2 is equivalent to 1.2.0, 
1.2.0.0, and so on. However use searches for modules matching a version 
prefix, so the subversions are wildcarded, and in this context :ver<1.2> 
really means :ver<1.2.*>."

So it sounds like zef does want some smart matching of versions, but not 
according to the same rules as Version implements.

> Would it be possible for both v1.1 and v1.1.0 to have been installed over
> a lengthy period

We must not allow that as according to the quoted rules those versions are 
equivalent.

> I think technically you could install such distributions into raku

I fear so, too. Clearly a bug.

**Comment by ugexe** [comment]
`:ver<1.2>` cannot mean `:ver<1.*`>, because then `use Test:ver<6.c.1.2.3.4.5>` will load `Test:ver<6.c>` which is wrong. If one really wants such behavior then they should explicitly say so via `:ver<6.c.*>`

**Comment by ugexe** [comment]
> Saying 1.2.1 specifies an exact match *on that part* of the version number, not a minimum match.

If was the reality then there would be no way to `use` a precise version ( which is what https://github.com/rakudo/rakudo/pull/1118#issue-131441837 addressed for one side of the smart match )

**Comment by tbrowder** [comment]
I'm having possibly a similar or related issue. I have a module PDF::Writer which is currently at v0.0.5. There is an older module of the same name as part of an older PDF (by another author, DWARRING), but PDF is now at version v0.4.5 and it no longer has a module named PDF::Writer.

**Comment by ugexe** [comment]
@tbrowder are you sure you don't have PDF v0.4.5 in the zef cache (which you can see via `--verbose` or `--debug` flags)? It wouldn't matter if it didn't exist in the p6c or cpan ecosystems anymore -- it might exist as part of some future ecosystem that doesn't remove old versions, a darkpan, or a caching mechanism -- as long as zef sees it and can compare with whatever version it claims to be.

**Comment by tbrowder** [comment]
On Wed, Jan 6, 2021 at 09:57 Nick Logan <notifications@github.com> wrote:

> @tbrowder <https://github.com/tbrowder> are you sure you don't have PDF
> v0.4.5 in the zef cache
>
I'll check more closely and report back...
