### ISSUE TITLE
zef install "Some::Module:auth<someone>" doesn't work when its author is defined by "author" instead of "auth"

### ISSUE THREAD

**Issue by titsuki** [ugexe/zef#393]
## Context

I found that `$ zef install Term::termios:auth<github:krunen>` doesn't work and this module defines its author by the "author" field instead of "auth": https://github.com/krunen/term-termios/blob/master/META6.json#L5
AFAIK, previous version of zef could use both "author" and "auth" in META6.json interchangeably and `$ zef install Term::termios:auth<github:krunen>` did work.

## Expected Behavior

`$ zef install Term::termios:auth<github:krunen>` works

## Actual Behavior

`$ zef install Term::termios:auth<github:krunen>` fails:
```
===> Searching for: Term::termios:auth<github:krunen>
No candidates found matching identity: Term::termios:auth<github:krunen>
```

(I also found that `$ zef install Term::termios:author<github:krunen>` works)

## Your Environment

* raku -v
```
$ raku -v
This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.
```
* zef list --installed
```
$ zef list --installed

===> Found via /home/itoyota/rakudo-star-2020.01/install/share/perl6/site
Algorithm::LBFGS:ver<0.0.6>:auth<cpan:TITSUKI>
App::AizuOnlineJudge:ver<0.0.4>:auth<cpan:TITSUKI>
App::Mi6:ver<0.3.1>:auth<cpan:SKAJI>
App::Mi6:ver<1.0.0>:auth<cpan:SKAJI>
App::Prove6:ver<0.0.12>:auth<cpan:LEONT>
Base64:ver<0.0.2>:auth<github:ugexe>
CPAN::Uploader::Tiny:ver<0.0.6>:auth<cpan:SKAJI>
Chart::Gnuplot:ver<0.0.17>:auth<cpan:TITSUKI>
Cro::Core:ver<0.8.3>
Cro::HTTP:ver<0.8.3>
Cro::TLS:ver<0.8.3>
Cro::WebSocket:ver<0.8.3>
Crypt::Random:ver<0.4.1>:auth<github:skinkade>
DBIish:ver<0.5.19>
DOM::Tiny:ver<0.5.2>:auth<github:zostay>
DateTime::Format
DateTime::Parse:ver<0.9.1>
Debugger::UI::CommandLine
Digest::HMAC:ver<1.0.2>:auth<github:retupmoca>
Digest::MD5:ver<0.05>:auth<Cosimo Streppone>
Digest::SHA1::Native:ver<0.04>
Digest:ver<0.3.4>:auth<Lucien Grondin>
Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
Docker::File:ver<1.0>:auth<github:jnthn>
Encode:ver<0.0.3>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Ignore:ver<1.1>:auth<Jonathan Worthington <jnthn@jnthn.net>>
File::Temp:ver<0.0.6>
File::Which:ver<1.0.1>
Geo::Hash:ver<0.0.2>:auth</home/itoyota/Programs/raku-Geo-Hash/resources/libraries/libgeohash.so
>
Geo::Hash:ver<0.0.2>:auth<cpan:TITSUKI>
Geo::Hash:ver<0.0.3>:auth<cpan:TITSUKI>
Getopt::Long:ver<0.1.3>
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>
Grammar::Profiler::Simple:ver<0.02>
HTTP::Easy:ver<1.1.0>
HTTP::HPACK:ver<0.9.2>
HTTP::Status
HTTP::Tinyish:ver<0.1.4>:auth<cpan:SKAJI>
HTTP::UserAgent:ver<1.1.49>:auth<github:sergot>
IO::Capture::Simple
IO::Path::ChildSecure:ver<1.001011>
IO::Socket::Async::SSL:ver<0.7.5>
IO::Socket::SSL:ver<0.0.1>:auth<github:sergot>
IO::String:ver<0.1.1>:auth<Rob Hoelz>
JSON::Class:ver<0.0.14>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.10>
JSON::JWT:ver<1.0>:auth<github:retupmoca>
JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
JSON::Pretty:ver<0.1.0>:auth<github:FROGGS>
JSON::RPC:ver<1.0.0>:auth<bbkr>
JSON::Tiny:ver<1.0>
JSON::Unmarshal:ver<0.08>
LWP::Simple:ver<0.106>:auth<github:perl6>
LibraryCheck:ver<0.0.9>:auth<github:jonathanstowe>:api<1.0>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.7.1>:auth<github:jonathanstowe>:api<1.0>
Log::Timeline:ver<0.3>
META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
NativeHelpers::Blob:ver<0.1.12>:auth<github:salortiz>
OO::Monitors:ver<1.1.1>
OpenSSL:ver<0.1.22>:auth<github:sergot>
PSGI:ver<1.2.0>
Pod::Load:ver<0.5.5>
Pod::To::BigPage:ver<0.5.1>:auth<Perl 6>
Pod::To::HTML:ver<0.6.2>:auth<Perl 6>
Pod::To::Markdown:ver<v.0.1.4>
Readline:ver<0.1.5>:auth<github:drforr>
SVG
SVG::Plot
Shell::Command
System::Query:ver<0.1.4>:auth<github:tony-o>
TAP:ver<0.1.0>
Temp::Path:ver<1.001007>
Template::Mojo:ver<v.0.1>
Template::Mustache:ver<1.0.1>:auth<github:softmoth>
Term::termios:auth<github:krunen>
Terminal::ANSIColor:ver<0.5>
Terminal::Getpass:ver<0.0.6>
Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
Test::Mock:ver<1.5>
Test::Output:ver<1.001002>
Test::Util::ServerPort:ver<0.0.2>:auth<github:jonathanstowe>:api<1.0>
Test::When:ver<1.001008>
Testo:ver<1.003006>
URI:ver<0.3.0>
XML::Writer
YAMLish:ver<0.0.5>
cro:ver<0.8.3>
if:ver<0.1.1>:auth<github:FROGGS>
p6doc:ver<1.003>:auth<perl6>
zef:ver<0.11.2>:auth<github:ugexe>:api<0>
zef:ver<0.8.2>:auth<github:ugexe>:api<0>
===> Found via /home/itoyota/rakudo-star-2020.01/install/share/perl6/core
CORE:ver<6.d>:auth<perl>
```

**Comment by ugexe** [comment]
This change was intentional -- the only reason it ever worked at all was to be bug compatible with various bits of pre-6c code, as s22 itself only mentions the `authors` (not `author`) field. The original behavior was otherwise confusing, and would require any type of code trying to understand what namespace something represents to know the heuristics to apply.

I would suggest updating META6.json to have an `auth` field if at all possible. I could potentially (and temporarily) restore the old behavior if needed, but I'm hoping that won't be required since I will eventually remove this inconsistency from rakudo as well.

> (I also found that $ zef install Term::termios:author<github:krunen> works)

You can't search on author when importing using core raku `CompUnit::Repository`s (`use Term::termios:author<github:krunen>` is the same as `use Term:foo<bar>` is the same as `use Term`), so the above would be the same as `$ zef install Term` (which likely still matches what you expected). Theoretically some zef ecosystem backend (or external `CompUnit::Repository`) might do something with currently unused/unknown fields (like `:author<...>`, or something like `:md5<...>`), and hence they ignore unknown fields to be future compatible with plugins/external CURs.

---

As an aside this isn't the only inconsistency in this area. There is `:ver` vs `:version` -- we all use `version`, but e.g. `use Test:version<XXX>` is the same as `use Test` not `use Test:ver<XXX>`. Hopefully we can figure out the best way to fix that eventually (maybe just parse `:version` from `use`), but the `auth`/`author`/`authority` is worse and thus happens to be getting action first.
