### ISSUE TITLE
zef may fetch zef-authed distributions from non-zef ecosystem

### ISSUE THREAD

**Issue by skaji** [ugexe/zef#396]
## Context

I believe one of the reasons to create a new ecosystem "zef ecosystem" is
that it ensures that the auth matches.

Practically, it means that,
if people execute `zef install 'ModuleX:auth<zef:skaji>'`,
they may assume "we have ModuleX released by zef:skaji".

But currently, it seems that zef may fetch zef-authed distributions from non-zef ecosystem, for example, p6c ecosystem.

## Expected Behavior

I don't know yet.

## Actual Behavior

Fetch `ModuleX:auth<zef:skaji>` from p6c ecosystem.

### Step1: Prepare the following app.psgi
 
```perl
# app.psgi
use strict;
use warnings;

my $fez = <<'EOF';
[
    {
        "auth": "zef:skaji",
        "name": "ModuleX",
        "version": "1",
        "source-url": "https://example.com/ModuleX-fez.tar.gz",
        "provides": {
            "ModuleX": "lib/ModuleX.rakumod"
        }
    }
]
EOF

my $cpan = <<'EOF';
[
]
EOF

my $p6c = <<'EOF';
[
    {
        "auth": "zef:skaji",
        "name": "ModuleX",
        "version": "2",
        "source-url": "https://example.com/ModuleX-p6c.tar.gz",
        "provides": {
            "ModuleX": "lib/ModuleX.rakumod"
        }
    }
]
EOF

sub {
    my $env = shift;
    my $path = $env->{PATH_INFO};
    if ($path eq "/fez.json") {
        [200, [], [$fez]];
    } elsif ($path eq "/cpan.json") {
        [200, [], [$cpan]];
    } elsif ($path eq "/p6c.json") {
        [200, [], [$p6c]];
    } else {
        [404, [], ["not found"]];
    }
};
```

### Step2: Run app.psgi

```
❯ plackup app.psgi
HTTP::Server::PSGI: Accepting connections at http://0:5000/
```

### Step3: Turn zef to localhost:5000

```diff
diff --git resources/config.json resources/config.json
index 4ae237b..db6d77e 100644
--- resources/config.json
+++ resources/config.json
@@ -30,9 +30,8 @@
             "options": {
                 "name": "fez",
                 "auto-update": 1,
-                "uses-path": true,
                 "mirrors": [
-                    "http://360.zef.pm/"
+                    "http://localhost:5000/fez.json"
                 ]
             }
         },
@@ -50,9 +49,7 @@
                 "name" : "cpan",
                 "auto-update" : 1,
                 "mirrors" : [
-                    "https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json",
-                    "https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json",
-                    "git://github.com/ugexe/Perl6-ecosystems.git"
+                    "http://localhost:5000/cpan.json"
                 ]
             }
         },
@@ -64,9 +61,7 @@
                 "name" : "p6c",
                 "auto-update" : 1,
                 "mirrors" : [
-                    "https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json",
-                    "git://github.com/ugexe/Perl6-ecosystems.git",
-                    "http://ecosystem-api.p6c.org/projects1.json"
+                    "http://localhost:5000/p6c.json"
                 ]
             }
         },
```

### Step4: Install `ModuleX:auth<zef:skaji>`

```
❯ rm -rf ~/.zef && raku -Ilib bin/zef install 'ModuleX:auth<zef:skaji>'
===> Searching for: ModuleX:auth<zef:skaji>
===> Updating fez mirror: http://localhost:5000/fez.json
===> Updating cpan mirror: http://localhost:5000/cpan.json
===> Updating p6c mirror: http://localhost:5000/p6c.json
===> Updated fez mirror: http://localhost:5000/fez.json
===> Updated cpan mirror: http://localhost:5000/cpan.json
===> Updated p6c mirror: http://localhost:5000/p6c.json
===> Extraction: Failed to find a META6.json file for ModuleX:ver<2>:auth<zef:skaji> -- failure is likely
[ModuleX] Extracting with plugin Zef::Service::Shell::tar+{<anon|1>} aborted.
Type check failed for return value; expected IO::Path but got Any (Any)
```

Then you'll see

```
Extraction: Failed to find a META6.json file for ModuleX:ver<2>:auth<zef:skaji>
```

which means zef fetch `ModuleX:ver<2>:auth<zef:skaji>` from p6c ecosystem, not from zef ecosystem.

## Your Environment

* raku -v
    ```
    Welcome to Rakudo(tm) v2021.02.1.
    Implementing the Raku(tm) programming language v6.d.
    Built on MoarVM version 2021.02.
    ```
* zef list --installed
    ```
    ===> Found via /Users/skaji/env/rakuenv/versions/2021.02.1-01/share/perl6/site
    zef:ver<0.11.4>:auth<github:ugexe>:api<0>
    ===> Found via /Users/skaji/env/rakuenv/versions/2021.02.1-01/share/perl6/core
    CORE:ver<6.d>:auth<perl>
    ```

**Comment by ugexe** [comment]
The `auth` field isn't for authors to say where one must obtain some module (like dependencies) -- its more of a tool for ecosystems (verify the author; decide who owns a namespace without explicit `auth` attached) and darkpans (providing alternative modules if some module has `use Foo:auth<zef:blorg>;` we want a darkpan to be able to provide that if they so choose).

Better ecosystems would not allow arbitrary `auth` (like how e.g. p6c does), so if enough modules end up in these stricter ecosystems eventually then p6c would get disabled by default in zef (for example right now you could run zef with `zef --/p6c ...` and then the other ecosystem isn't in play). This means the problem goes away in the common case since the stricter ecosystems would only allow / manage the auth strings they index, and those strict ecosystems are the only ones in use. Users then would do like `zef --p6c ...` to enable p6c and get access to experimental stuff from ecosystems that don't verify anything about the distribution itself. All that to say if we could disable e.g. p6c by default there is no problem.

I've also considered tiering the ecosystems such that ecosystems in e.g. group 0 get used first, and ecosystems in group 1 only get used if no match was found in group 0 (even if group 1 would have a higher version). This could also potentially avoid the issue without disabling p6c by default since it would grab the highest version from `zef` first.
