### ISSUE TITLE
Compress::Zlib::Raw installation failure

### ISSUE THREAD

**Issue by azawawi** [ugexe/zef#68]
```Compress::Zlib::Raw``` cannot be installed using ```zef``` because it is using ```Panda::Builder```. Please see:
https://github.com/retupmoca/P6-Compress-Zlib-Raw/blob/master/Build.pm

What is zef's API solution to such a problem?

**Comment by ugexe** [comment]
Zef can install things using Build.pm files. Zefs alternative, which is dependency free, is modeled after the hooks implementation found in s22.

That Build.pm has a 'use Panda::Builder' but doesn't list panda as a dependency like it should. On the other hand panda shouldn't require that the class it looks for in Build.pm actually is 'Panda::Builder' because it has no bearing on the result (but forces a depensency on a specific module installer). As such 'use Panda::Builder' can be replaced with 'my class Panda::Builder {}' so it fakes it while still working and without the dependency. Please see point 2 here: ugexe.com/5-tips-for-writing-better-perl6-modules

**Comment by ugexe** [comment]
Zef can install things using Build.pm files. Zefs alternative, which is dependency free, is modeled after the hooks implementation found in s22.

That Build.pm has a 'use Panda::Builder' but doesn't list panda as a dependency like it should. On the other hand panda shouldn't require that the class it looks for in Build.pm actually is 'Panda::Builder' because it has no bearing on the result (but forces a depensency on a specific module installer). As such 'use Panda::Builder' can be replaced with 'my class Panda::Builder {}' so it fakes it while still working and without the dependency. Please see point 2 here: http://ugexe.com/5-tips-for-writing-better-perl6-modules

**Comment by ugexe** [comment]
This issue is resolved, although there is still an issue. `Shell::Command` appears to fail to install on windows which is a build dependency of `Compress::Zlib::Raw`. However, the single call to `cp` used in the `Build.pm` file could be replaced with a `copy()` and a line or two of logic, removing `Shell::Command` as a dependency all together.

**Comment by azawawi** [comment]
Thanks :+1:
