### ISSUE TITLE
Failure to install on Windows 7 64-bit

### ISSUE THREAD

**Issue by azawawi** [ugexe/zef#71]
```
d:\tools\zef>perl6 -Ilib bin/zef install .
Initializing
===> Fetching   The spawned process exited unsuccessfully (exit code: 259)
  in sub git-ls at D:\tools\zef\lib\Zef\App.pm6:581
  in sub git-package-json at D:\tools\zef\lib\Zef\App.pm6:606
  in sub packages at D:\tools\zef\lib\Zef\App.pm6:548
  in block  at D:\tools\zef\lib\Zef\App.pm6:399
  in sub CLI-WAITING-BAR at D:\tools\zef\lib\Zef\CLI.pm6:134
  in sub MAIN at D:\tools\zef\lib\Zef\App.pm6:386
  in sub MAIN at D:\tools\zef\lib\Zef\App.pm6:202
  in block <unit> at bin/zef:3
```

Perl 6 version:

```
d:\tools\zef>perl6 --version
This is perl6 version 2015.10-232-g460d89d built on MoarVM version 2015.10-61-g624d504
```

**Comment by ugexe** [comment]
This appears resolved with https://github.com/ugexe/zef/commit/904c16f583d239f05e75fc080ecf147ca30d879c as tested on Windows 10 and Windows 8 by manually splitting output lines instead of relying on rakudo to do the right thing (for now)

**Comment by azawawi** [comment]
```
d:\tools\zef>perl6 -Ilib bin/zef install .
Initializing
===> Fetching   The spawned process exited unsuccessfully (exit code: -16)
  in sub git-ls at D:\tools\zef\lib\Zef\App.pm6:586
  in sub git-package-json at D:\tools\zef\lib\Zef\App.pm6:618
  in sub packages at D:\tools\zef\lib\Zef\App.pm6:548
  in block  at D:\tools\zef\lib\Zef\App.pm6:399
  in sub CLI-WAITING-BAR at D:\tools\zef\lib\Zef\CLI.pm6:134
  in sub MAIN at D:\tools\zef\lib\Zef\App.pm6:386
  in sub MAIN at D:\tools\zef\lib\Zef\App.pm6:202
  in block <unit> at bin/zef:3
```
on my box

**Comment by ugexe** [comment]
We found a bug in #perl6 where `try { run "asdf" }; say 1;` will not execute the `say 1` without sinking inside the try block which explains why it dies with an exception. Then I checked on windows and found another bug in rakudo's `Proc` where, for a failed process, the return value is `-1` on linux but `-16` on windows.

I re-tested and it still worked on my end. So I think it must be related to the commands I used to clone and update the package list repo. I suspect there are unmerged updates from `fetch` and if you delete `c:\user\name\.zef` (or `.zef` in whatever folder `$*HOME` points to) it will work. I changed the `fetch` to a `pull` so that updates are simply merged in automatically.

If it still fails after deleting that folder and pulling these latest changes could you run the follow commands in the zef directory? (it would help me determine why git is being uncooperative in some cases but not others)

    git update-index
    git ls-files
    git pull -n --update-shallow --depth=1

**Comment by azawawi** [comment]
I found the problem I previously cloned `zef` in `d:\tools` and not in `%USERPROFILE%\zef`.

`zef` is working again perfectly for me again. Do you think `zef` is assuming too much during installation?

I assumed that it works like `panda rebootstrap.pl` and that was my downfall. My bad.

**Comment by ugexe** [comment]
Hmm you shouldn't have to clone zef to any specific directory, that
directory should just be for config stuff and the package list. Did you
happen to try after clearing the .zef directory? Maybe doing the clone
there meant you had to erase the previous package list repo? Otherwise
there may still be a problem as it should work like you expect.

**Comment by azawawi** [comment]
- Tried it after removing `.zef` and `zef` from %USERPROFILE%` directory.
- git repo was at `d:\tools\zef`.
- Same problem occurred and an empty `%USERPROFILE%\.zef\git` was created.

**Comment by ugexe** [comment]
Closing this. The refactor replaced the entire code base so this may or may not be true anymore. I've successfully used it on windows 10 and 8 however. If the new version of zef still fails for you please feel free to re-open!
