### ISSUE TITLE
`panda installdeps .` replacement in zef

### ISSUE THREAD

**Issue by azawawi** [ugexe/zef#82]
What's `panda installdeps .` replacement in zef?

**Comment by ugexe** [comment]
The zef replacement is `zef --depsonly install .`

One may ask, "Why not use a separate command, installdeps?" My current thought is that since `install` and `installdeps` would share all the same code except for a single `grep` (to remove the non-dependencies from the candidate list, which they still must be *fetched* from to get the update-to-date dependency list from its META6) that its better as an option/flag to a single command `install`. It is true that it would be trivial to add a thin `multi MAIN('installdeps'` function to delegate to `multi MAIN('install'`, but a new command would also require documentation (including all the parameters, which would be redundant between `installdeps` and `install`, like the `--["-" [build|test]]?depends` flags).

Note that `--depsonly` appears to have stopped working as of 10 days ago (last known good revision 2ec83dd). However it has been fixed as of today.

Also note that I do not really like the name `depsonly` as it implies a type of exclusion or false boolean in the name itself. I'd prefer using an actual negative flag like the `depends` options use  (`--depends --/depends` `--test-depends --/test-depends` `--build-depends --/build-depends`, where the default values are positive (True)). Something like `--/requested` (where "requested" means not a dependency) where the default is `--requested`, but I can't think of a word/term that would make sense to a newer user (--requested might make sense to someone intimately familiar with `zef`, but probably not a newer user). In other words instead of `zef --depsonly install .` i'd prefer `zef --/requested install .` Notice the negative is implied by the command, `--/`, instead of by the text like `only` or other common uses like `skip` and `no` (hence `zef` uses `--/test` instead of `--skip-test` or `--notest`).

If anyone can think of a flag to replace `--depsonly` that fits this scheme i'd love to hear it.

**Comment by azawawi** [comment]
Thanks for fixing it. It works perfectly now. I wish we had more example documentation (i.e. cookbook style) :+1: 

I vote for `zef --installdeps .` since it is compatible with `cpanm --installdeps .`. Thus, it will make the future transition to Perl 6 easier for most Perl programmers. Also we can have another alias for purists `zef --install-deps .`.

**Comment by azawawi** [comment]
Another related bug when there is no dependencies, it croaks with the following error:

```
rakudobrew build zef
Cloning into 'zef'...
Your branch is up-to-date with 'origin/master'.
===> Testing: zef:auth('github:ugexe')
t/00-load.t ........... ok
t/identity.t .......... ok
t/utils-filesystem.t .. ok
All tests successful.
Files=3, Tests=14, 109 wallclock secs ( 0.22 usr +  0.05 sys =  0.27 CPU)
Result: PASS
===> Testing [OK] for zef:auth('github:ugexe')
===> Installing: zef:auth('github:ugexe')
===> Install [OK] for zef:auth('github:ugexe')
 
1 bin/ script [zef] installed to:
C:\Users\appveyor\rakudobrew\moar-2016.02\install\share\perl6\site\bin
Updating shims
Done, built zef for moar-2016.02
cd %APPVEYOR_BUILD_FOLDER%
zef --depsonly install .
All candidates are currently installed. No reason to proceed (use --force to continue anyway)
  in sub MAIN at C:\Users\appveyor\rakudobrew\moar-2016.02\install\share\perl6\site\sources\A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 line 105
  in block <unit> at C:\Users\appveyor\rakudobrew\moar-2016.02\install\share\perl6\site/resources/EA5AB4A8FDBB356B44B048C7BEA933AE333F7E49 line 1
 
Command exited with code 1
```

**Comment by azawawi** [comment]
Looks good. Thanks :+1: 

https://ci.appveyor.com/project/azawawi/perl6-file-which/build/1.0.15
