### ISSUE TITLE
Fails to install Linenoise

### ISSUE THREAD

**Issue by xdg** [ugexe/zef#93]
```
$ perl6 --version
This is Rakudo version 2016.06-21-gfd98fc3 built on MoarVM version 2016.06
implementing Perl 6.c.
```

```
$ zef install Linenoise
===> Searching for: Linenoise
===> Searching for missing dependencies: Native::Resources
===> Searching for missing dependencies: LibraryMake
===> Searching for missing dependencies: Shell::Command
===> Searching for missing dependencies: File::Which, File::Find
===> Fetching: Linenoise
===> Fetching: Native::Resources
===> Fetching: LibraryMake
===> Fetching: Shell::Command
===> Fetching: File::Find
===> Fetching: File::Which
===> Building: Linenoise:ver('0.1.0'):auth('Rob Hoelz')
`build-depends` is missing entries. Attemping to mimick missing dependencies...
Cannot invoke this object (REPR: Null; VMNull)
  in sub get-vars at /Users/david/.zef/store/P6-LibraryMake.git/8ab4b23a981ebfd63a74c11d1398750a472195aa/lib/Librar
yMake.pm6 (LibraryMake) line 95
  in sub get-vars at /Users/david/.zef/store/p6-native-resources.git/b05fd025d5a3541e88b5acc266446d3814d79cc0/lib/N
ative/Resources/Build.pm (Native::Resources::Build) line 13
  in sub make at /Users/david/.zef/store/p6-native-resources.git/b05fd025d5a3541e88b5acc266446d3814d79cc0/lib/Nativ
e/Resources/Build.pm (Native::Resources::Build) line 27
  in method build at /Users/david/.zef/store/p6-linenoise.git/46f9534b1568e68a2a077ee80713914738b16e28/Build.pm (Bu
ild) line 13
  in block <unit> at -e line 1

===> Building [FAIL]: Linenoise:ver('0.1.0'):auth('Rob Hoelz')
===SORRY!===
Aborting due to build failure: Linenoise:ver('0.1.0'):auth('Rob Hoelz')(use --force to override)
```

Installing with panda worked fine.

**Comment by ugexe** [comment]
The fact panda can install it is either a coincidence or indicative of a import/precomp bug

zef launches the Build script in a new process. To keep the example short assume all depends were already installed via `zef --depsonly install Linenoise`. The build is then executed with:
`perl6 -I. -e 'require ::("Build"); say ::("Build").new.build("/Users/david/.zef/store/p6-native-resources.git/b05fd025d5a3541e88b5acc266446d3814d79cc0");'`
(If they are not already installed zef passes the proper paths with `-I`)

If you actually try this you'll get an error, and this is related to `Linenoise` failing to declare all its depends. So you'd need to edit `Build.pm` and `s/use Panda::Builder//` and `s/is Panda::Builder//;` (which zef does automatically, and `Linenoise` should add `panda` to its depends or modify their `Build.pm` accordingly). There is no need for `Panda::Builder` or for the `Build.pm` class to inherit from it; this is an artifact from long ago when `panda` would use `isa` to check if the class was a `Panda::Builder` which also meant you could not write a `Build.pm` that was both able to be executed on its own *and* understandable to `panda`. Alternatively you can just install `panda` and not have to edit the file at all. I've tested both cases and they give this same error.

If you look at [Panda::Builder](https://github.com/tadzik/panda/blob/master/lib/Panda/Builder.pm) you'll see its just as simple. The two differences are it `require "Build.pm"` vs zef's `require ::("Build")`, and this itself is also due to a rakudobug (`perl6 -I. -e 'require "Build.pm"; say ::("Build").new'` will fail, whereas with `require ::("Build")` it will work). The other difference is that its panda is `require`ing the `Build.pm` into its own mainline (This can lead to a bad `Build.pm` to poison panda and, for instance, cause all remaining modules being smoke tested to fail)

Now that I've written this wall of text I've come up with a workaround (and I say workaround because this actually a new rakudo bug):
`perl6 -I. -MBuild -e 'say ::("Build").new.build($path);'`

Thanks for the heads up!
