### ISSUE TITLE
zef should recognize Build.pm6 as same as Build.pm

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#98]
may not be possible due to other dependencies

**Comment by ugexe** [comment]
Theoretically you are correct. `Build.pm`, however, is not specced and is really just an artifact from many years ago. `zef` has to bend over backwards in many places just to make the current implementations work as its original designed tied it to panda. In other words: it will eventually be replaced by something better.

So why not just allow the `.pm6` extension? Because:
1. it would not be compatible with `panda`
2. it leaves the `.pm6` extension available to accept a new, better Build hook
3. a better system *must* be created/agreed on anyway
